version: '2'
services:
  cpsrv:
    build:
      context: .
      dockerfile: docker/dockerfile_cpsrv
    volumes:
      - ./data/banks:/var/lib/cpsrv/data/banks:ro
      - ./data/GoogleAuth.html:/usr/data/GoogleAuth.html:ro
    depends_on:
      - tarantool
    networks:
      - front-tier
      - back-tier

  tarantool:
    image: tarantool/tarantool
    volumes:
      - ./tnt_workdir/init_common.lua:/var/lib/cpsrv/lua/init_common.lua:ro
      - ./tnt_workdir/init_docker.lua:/var/lib/cpsrv/lua/init.lua:ro
      - ./tnt_workdir/api:/var/lib/cpsrv/lua/api:ro
      - ./tnt_workdir/snap:/var/lib/cpsrv/snap
      - ./tnt_workdir/wal:/var/lib/cpsrv/wal
    command: ["tarantool", "/var/lib/cpsrv/lua/init.lua"]
    networks:
      - back-tier
  nginx:
    image: nginx:alpine
    volumes:
      - ./data/GoogleAuth.html:/usr/share/nginx/html/GoogleAuth.html:ro
      - ./data/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cpsrv
    networks:
      - front-tier
    ports:
      - "8080:80"
networks:
  front-tier:
  back-tier:
